name: aqueduct
version: 4.0.0-b2
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
homepage: https://aqueduct.io
documentation:

environment:
  sdk: ">=2.0.0 <2.12.0"

dependencies:
  args: ^1.6.0
  analyzer: '>=0.39.4 <0.41.0'
  crypto: ^2.0.6
  logging: ^0.11.4
  isolate_executor:
    git:
      url: https://github.com/jayjah/dart-isolate-executor.git
      ref: master
  meta: ^1.1.5
  open_api:
    git:
      url: https://github.com/jayjah/open-api-dart.git
      ref: master
  password_hash:
    git:
      url: https://github.com/jayjah/dart-password-hash.git
      ref: master
  path: ^1.6.1
  postgres:
    git:
      url: https://github.com/jayjah/postgresql-dart.git
      ref: master
  pub_cache:
    git:
      url: https://github.com/jayjah/pub_cache.git
      ref: master
  pub_semver: ^1.4.4
  safe_config:
    git:
      url: https://github.com/jayjah/safe_config.git
      ref: master
  yaml: ^2.1.15
  runtime:
    git:
      url: https://github.com/jayjah/dart-runtime.git
      ref: master

dev_dependencies:
  matcher: '>=0.12.3 <0.14.0'
  test: ^1.3.0
  http: '>=0.11.3+7 <0.13.0'
  aqueduct_test:
    path: aqueduct_test

executables:
  aqueduct: aqueduct