name: aqueduct_test
description: Utilities for writing automated tests for Aqueduct applications
version: 2.0.0-b1
homepage: https://github.com/stablekernel/aqueduct
author: stable|kernel <jobs@stablekernel.com>
documentation:

environment:
  sdk: ">=2.0.0 <2.12.0"

dependencies:
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'
  # fork: backend framework
  # BSD-License
  # https://pub.dev/packages/aqueduct
  aqueduct:
    git:
      url: https://github.com/jayjah/aqueduct.git

# This is removed before being published.
dependency_overrides:
  aqueduct:
    path: ../